
const microsites = ['ATLAS', 'AZ CTE', 'CT', 'CUNY', 'INFOHIO', 'LOUIS', 'MI',  'MOST', 'NCCCS', 'NCDPI', 'NHC', 'OER Commons', 'OH', 'SHMS', 'SWS', 'THECB', 'UEN', 'VADOE', 'VIDE', 'VIVA', 'WI']

      // [
      //   {
      //     micrositeTitle: `ATLAS`,
      //     id: 1,
      //     collectionTitle: `Discover CCSS Aligned English Language Arts`,
      //     collectionThumbnail: '1.jpeg',
      //     resourcesNumber: 22,
      //     modifiedDate: `May 4, 2020`,
      //   },
      //   {
      //     micrositeTitle: `ATLAZ CTEAS`,
      //     id: 2,
      //     collectionTitle: `Discover CCSS Aligned Mathematics`,
      //     collectionThumbnail: '2.jpeg',
      //     resourcesNumber: 122,
      //     modifiedDate: `December 24, 2021`,
      //   },
      //   {
      //     micrositeTitle: `CT`,
      //     id: 3,
      //     collectionTitle: `NGSS`,
      //     collectionThumbnail: '3.png',
      //     resourcesNumber: 12,
      //     modifiedDate: `April 14, 2019`,
      //   },
      //   {
      //     micrositeTitle: `INFOHIO`,
      //     id: 4,
      //     collectionTitle: `STEAM`,
      //     collectionThumbnail: '4.jpeg',
      //     resourcesNumber: 26,
      //     modifiedDate: `October 13, 2021`,
      //   },
      //   {
      //     micrositeTitle: `LOUIS`,
      //     id: 5,
      //     collectionTitle: `TeachEngineering`,
      //     collectionThumbnail: '5.png',
      //     resourcesNumber: 267,
      //     modifiedDate: `November 19, 2020`,
      //   },
      //   {
      //     micrositeTitle: `MI`,
      //     id: 6,
      //     collectionTitle: `PheT Interactives`,
      //     collectionThumbnail: '6.jpeg',
      //     resourcesNumber: 67,
      //     modifiedDate: `June 18, 2021`,
      //   },
      //   {
      //     micrositeTitle: `MOST`,
      //     id: 7,
      //     collectionTitle: `Garden-Based Learning`,
      //     collectionThumbnail: '7.jpeg',
      //     resourcesNumber: 45,
      //     modifiedDate: `November 28, 2021`,
      //   },
      //   {
      //     micrositeTitle: `NCCCS`,
      //     id: 8,
      //     collectionTitle: `Folger Shakespeare Library`,
      //     collectionThumbnail: '8.jpeg',
      //     resourcesNumber: 27,
      //     modifiedDate: `october 6, 2021`,
      //   },
      //   {
      //     micrositeTitle: `NCDPI`,
      //     id: 9,
      //     collectionTitle: `Career and Technical Education (CTE)`,
      //     collectionThumbnail: '9.jpeg',
      //     resourcesNumber: 37,
      //     modifiedDate: `September 4, 2021`,
      //   },
      //   {
      //     micrositeTitle: `NHC`,
      //     id: 10,
      //     collectionTitle: `Game-Based Learning`,
      //     collectionThumbnail: '10.jpeg',
      //     resourcesNumber: 74,
      //     modifiedDate: `May 2, 2021`,
      //   },
      //   {
      //     micrositeTitle: `OER Commons`,
      //     id: 11,
      //     collectionTitle: `PheT Interactives`,
      //     collectionThumbnail: '11.jpeg',
      //     resourcesNumber: 87,
      //     modifiedDate: `July 1, 2021`,
      //   },
      // ]